export const Permissions = {
  CREATE_ROLES: 'Crear Roles',
  EDIT_ROLES: 'Editar Roles',
  DELETE_ROLES: 'Eliminar Roles',
  VIEW_ROLES: 'Ver Roles',
  MANAGE_PERMISSIONS: 'Gestionar Permisos',
  VIEW_USERS: 'Ver Usuarios',
  CREATE_USERS: 'Crear Usuarios',
  EDIT_USERS: 'Editar Usuarios',
  DELETE_USERS: 'Eliminar Usuarios',
  VIEW_INGRESO: 'Ver Ingresos',
  CREATE_INGRESO: 'Crear Ingresos',
  EDIT_INGRESO: 'Editar Ingresos',
  DELETE_INGRESO: 'Eliminar Ingresos',
  ADMINISTRATION:'Administracion',
  VIEW_AVALUO: 'Ver Avaluos',
  CREATE_AVALUO: 'Crear Avaluos',
  EDIT_AVALUO: 'Editar Avaluos',
  DELETE_AVALUO: 'Eliminar Avaluos',  
  VIEW_INSPECTION: 'Ver Inspecciones',
  CREATE_INSPECTION: 'Crear Inspecciones',
  EDIT_INSPECTION: 'Editar Inspecciones',
  DELETE_INSPECTION: 'Eliminar Inspecciones',
  VIEW_VAL: 'Ver Valores',
  CREATE_VAL: 'Crear Valores',
  EDIT_VAL: 'Editar Valores',
  DELETE_VAL: 'Eliminar Valores',
};